name: home_dreams
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  cloud_firestore: ^6.0.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  flutter_paypal_payment: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_svg_provider: ^1.0.7
  get_it: ^8.2.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  modal_progress_hud_nsn: ^0.5.1
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.0+1
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart

flutter_intl:
  enabled: true
